import unittest
from unittest.mock import patch
from src import solve

EXAMPLE = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""".strip().splitlines()

ANSWER1 = 21
ANSWER2 = 40


class TestExample(unittest.TestCase):
    @patch("src.solve.read_input", return_value=list(EXAMPLE))
    def test_final_answer(self, _mock):
        answer = solve.solve()
        self.assertEqual(answer, ANSWER1)

    @patch("src.solve.read_input", return_value=list(EXAMPLE))
    def test_final_answer_2(self, _mock):
        answer_part2 = solve.solve(part=2)
        self.assertEqual(answer_part2, ANSWER2)
